MAPPING_1 = 1
MAPPING_2 = 2
MAPPING_BOTH = 3


SPARQL_HOST_NAME = 'vm62.nubes.stfc.ac.uk'

SPARQL_PORT = '3333'
SPARQL_DATASET = 'vocab'

SPARQL_UPDATE = 'http://%s:%s/%s/%s' % (SPARQL_HOST_NAME, SPARQL_PORT, SPARQL_DATASET, 'update')
SPARQL_QUERY = 'http://%s:%s/%s/%s' % (SPARQL_HOST_NAME, SPARQL_PORT, SPARQL_DATASET, 'sparql')
SPARQL_DATA = 'http://%s:%s/%s/%s' % (SPARQL_HOST_NAME, SPARQL_PORT, SPARQL_DATASET, 'data')


CCI = 'cci'
C4I = 'climate4impact'
CMIP = 'cmip'
GCOS = 'gcos'
GRIB = 'grib'
SKOS = 'skos'
GLOSSARY = 'glossary'

ONTOLOGIES = [CCI, C4I, CMIP, GCOS, GRIB, GLOSSARY]

NAME_SPACE = 'http://%s' % SPARQL_HOST_NAME

CCI_NAME_SPACE = '%s/%s#' % (NAME_SPACE, CCI)
C4I_NAME_SPACE = '%s/%s#' % (NAME_SPACE, C4I)
CMIP_NAME_SPACE = '%s/%s#' % (NAME_SPACE, CMIP)
GCOS_NAME_SPACE = '%s/%s#' % (NAME_SPACE, GCOS)
GRIB_NAME_SPACE = '%s/%s#' % (NAME_SPACE, GRIB)
GLOSSARY_NAME_SPACE = '%s/%s#' % (NAME_SPACE, GLOSSARY)

NAME_SPACE_MAP = {}
NAME_SPACE_MAP[CCI] = CCI_NAME_SPACE
NAME_SPACE_MAP[C4I] = C4I_NAME_SPACE
NAME_SPACE_MAP[CMIP] = CMIP_NAME_SPACE
NAME_SPACE_MAP[GCOS] = GCOS_NAME_SPACE
NAME_SPACE_MAP[GRIB] = GRIB_NAME_SPACE
NAME_SPACE_MAP[GLOSSARY] = GLOSSARY_NAME_SPACE

CSV_DIRECTORY = '../csv/'
DATA_DIRECTORY = '../data/'
HTML_DIRECTORY = '../html/'
MODEL_DIRECTORY = '../model/'

CITO = "http://purl.org/spar/cito/"
