name: widoco

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for all branches
on: 
  push:
    branches: [ '*' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy Java
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Download widoco
      run: mkdir widoco && wget -O widoco/widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.14/widoco-1.4.14-jar-with-dependencies.jar
  
    - name: Compile documentation
      run: |
        cd widoco        
        java -jar ./widoco.jar \
        -ontFile ../html/ontology/cci/cci-content/cci-ontology.ttl \
        -oops \
        -webVowl \
        -includeAnnotationProperties \
        -outFolder doc/ \
        -rewriteAll \
        -includeImportedOntologies \
        -uniteSections \
        -excludeIntroduction
        cd ..

		      -  name: Publish documentation to repo
         run: |-
            mkdir -p docs/widoco/
            cp -RT widoco/doc/* docs/widoco/
            cd docs/widoco/
            git config --local user.name "github-actions[bot]"
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Documentation update"
            git push